// Language-independent base data for all 101 items
const baseData = [
  {
    "id": "emirati-house",
    "num": 1,
    "category": "culture",
    "area": "Embassies District",
    "place": "Yadoo's House Restaurant & Cafe",
    "address": "Al Murror Street, Al Nasr Tower 2, Abu Dhabi",
    "station": "없음",
    "photo_folder": "emirati-house",
    "scores": {
      "photo": 3,
      "culture": 5,
      "activity": 2,
      "relaxation": 4,
      "peaceful": 3,
      "couple": 3,
      "family": 5,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4305,
      "lng": 54.4336
    },
    "gm_rating": 4.1,
    "gm_reviews": 968,
    "activity_rating": 4.1,
    "recommendation_score": 51,
    "overall_rank": 95,
    "category_rank": 16,
    "category_total": 18,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "golf-club",
    "num": 2,
    "category": "adventure",
    "area": "Al Mushrif",
    "place": "Abu Dhabi City Golf Club",
    "address": "Al Mushrif, Abu Dhabi, UAE",
    "station": "없음",
    "photo_folder": "golf-club",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 5,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 5,
      "tourist": 4,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4455,
      "lng": 54.3995
    },
    "gm_rating": 4.5,
    "gm_reviews": 1346,
    "activity_rating": 4.5,
    "recommendation_score": 58,
    "overall_rank": 84,
    "category_rank": 4,
    "category_total": 7,
    "fame_stars": 4,
    "uniqueness": 3
  },
  {
    "id": "adrenark",
    "num": 3,
    "category": "themepark",
    "area": "Yas Mall",
    "place": "Adrenark Adventure",
    "address": "Yas Mall, Yas Island, Abu Dhabi",
    "station": "Yas Mall",
    "photo_folder": "adrenark",
    "scores": {
      "photo": 4,
      "culture": 2,
      "activity": 5,
      "relaxation": 2,
      "peaceful": 1,
      "couple": 3,
      "family": 5,
      "solo": 3,
      "tourist": 4,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4881,
      "lng": 54.6074
    },
    "gm_rating": 4.5,
    "gm_reviews": 972,
    "activity_rating": 4.5,
    "recommendation_score": 88,
    "overall_rank": 21,
    "category_rank": 9,
    "category_total": 28,
    "fame_stars": 3,
    "uniqueness": 5
  },
  {
    "id": "airmaniax",
    "num": 4,
    "category": "themepark",
    "area": "Yas Mall",
    "place": "AirManiax",
    "address": "Yas Mall, Yas Island, Abu Dhabi",
    "station": "Yas Mall",
    "photo_folder": "airmaniax",
    "scores": {
      "photo": 3,
      "culture": 1,
      "activity": 5,
      "relaxation": 2,
      "peaceful": 1,
      "couple": 3,
      "family": 5,
      "solo": 2,
      "tourist": 4,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4881,
      "lng": 54.6074
    },
    "gm_rating": 4.9,
    "gm_reviews": 2421,
    "activity_rating": 4.9,
    "recommendation_score": 99,
    "overall_rank": 4,
    "category_rank": 1,
    "category_total": 28,
    "fame_stars": 4,
    "uniqueness": 5
  },
  {
    "id": "al-ain-adventure",
    "num": 5,
    "category": "adventure",
    "area": "Al Ain",
    "place": "Al Ain Adventure Park",
    "address": "Jebel Hafeet, Al Ain, Abu Dhabi",
    "station": "없음",
    "photo_folder": "al-ain-adventure",
    "scores": {
      "photo": 5,
      "culture": 2,
      "activity": 5,
      "relaxation": 3,
      "peaceful": 3,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 4,
      "accessibility": 3
    },
    "coordinates": {
      "lat": 24.0595,
      "lng": 55.76
    },
    "gm_rating": 4.4,
    "gm_reviews": 1538,
    "activity_rating": 4.4,
    "recommendation_score": 56,
    "overall_rank": 89,
    "category_rank": 5,
    "category_total": 7,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "al-fanar",
    "num": 6,
    "category": "dining",
    "area": "Yas Mall",
    "place": "Al Fanar",
    "address": "Yas Mall, Yas Island, Abu Dhabi",
    "station": "Yas Mall",
    "photo_folder": "al-fanar",
    "scores": {
      "photo": 3,
      "culture": 4,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 3,
      "couple": 4,
      "family": 3,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4881,
      "lng": 54.6074
    },
    "gm_rating": 4.9,
    "gm_reviews": 12016,
    "activity_rating": 4.9,
    "recommendation_score": 99,
    "overall_rank": 1,
    "category_rank": 1,
    "category_total": 18,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "al-qattara",
    "num": 7,
    "category": "culture",
    "area": "Al Ain",
    "place": "Al Qattara Arts Centre",
    "address": "Al Qattara, Al Ain, Abu Dhabi",
    "station": "없음",
    "photo_folder": "al-qattara",
    "scores": {
      "photo": 3,
      "culture": 5,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 3,
      "couple": 4,
      "family": 3,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.198,
      "lng": 55.6915
    },
    "gm_rating": 4.5,
    "gm_reviews": 632,
    "activity_rating": 4.5,
    "recommendation_score": 66,
    "overall_rank": 65,
    "category_rank": 10,
    "category_total": 13,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "al-raiqa",
    "num": 8,
    "category": "dining",
    "area": "Mina Zayed",
    "place": "Al Raiqa",
    "address": "Mina Zayed, Abu Dhabi",
    "station": "없음",
    "photo_folder": "al-raiqa",
    "scores": {
      "photo": 3,
      "culture": 4,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 3,
      "couple": 4,
      "family": 3,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.5165,
      "lng": 54.3725
    },
    "gm_rating": 4.4,
    "gm_reviews": 269,
    "activity_rating": 4.4,
    "recommendation_score": 49,
    "overall_rank": 96,
    "category_rank": 17,
    "category_total": 18,
    "fame_stars": 3,
    "uniqueness": 3
  },
  {
    "id": "al-sadeem",
    "num": 9,
    "category": "nature",
    "area": "Al Wathba",
    "place": "Al Sadeem Observatory",
    "address": "Al Wathba, Abu Dhabi",
    "station": "없음",
    "photo_folder": "al-sadeem",
    "scores": {
      "photo": 4,
      "culture": 4,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 3,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.1645,
      "lng": 54.6385
    },
    "gm_rating": 4.7,
    "gm_reviews": 213,
    "activity_rating": 4.7,
    "recommendation_score": 74,
    "overall_rank": 47,
    "category_rank": 2,
    "category_total": 4,
    "fame_stars": 3,
    "uniqueness": 5
  },
  {
    "id": "al-sultan",
    "num": 10,
    "category": "dining",
    "area": "Various",
    "place": "Al Sultan Bakeries",
    "address": "Various Locations, Abu Dhabi",
    "station": "지점별 상이",
    "photo_folder": "al-sultan",
    "scores": {
      "photo": 3,
      "culture": 4,
      "activity": 2,
      "relaxation": 4,
      "peaceful": 3,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.47,
      "lng": 54.37
    },
    "gm_rating": 4.3,
    "gm_reviews": 836,
    "activity_rating": 4.3,
    "recommendation_score": 61,
    "overall_rank": 74,
    "category_rank": 8,
    "category_total": 18,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "anantara-mangroves",
    "num": 11,
    "category": "beach",
    "area": "Eastern Mangroves",
    "place": "Anantara Eastern Mangroves",
    "address": "Eastern Mangroves, Abu Dhabi",
    "station": "없음",
    "photo_folder": "anantara-mangroves",
    "scores": {
      "photo": 5,
      "culture": 3,
      "activity": 3,
      "relaxation": 5,
      "peaceful": 5,
      "couple": 5,
      "family": 4,
      "solo": 5,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.4525,
      "lng": 54.435
    },
    "gm_rating": 4.5,
    "gm_reviews": 5067,
    "activity_rating": 4.5,
    "recommendation_score": 68,
    "overall_rank": 60,
    "category_rank": 10,
    "category_total": 17,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "anantara-santorini",
    "num": 12,
    "category": "beach",
    "area": "Mina Al Arab",
    "place": "Anantara Santorini",
    "address": "Mina Al Arab, Abu Dhabi",
    "station": "없음",
    "photo_folder": "anantara-santorini",
    "scores": {
      "photo": 5,
      "culture": 3,
      "activity": 3,
      "relaxation": 5,
      "peaceful": 5,
      "couple": 5,
      "family": 4,
      "solo": 5,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.5185,
      "lng": 54.368
    },
    "gm_rating": 4.8,
    "gm_reviews": 517,
    "activity_rating": 4.8,
    "recommendation_score": 68,
    "overall_rank": 61,
    "category_rank": 11,
    "category_total": 17,
    "fame_stars": 3,
    "uniqueness": 5
  },
  {
    "id": "annex",
    "num": 13,
    "category": "dining",
    "area": "Abu Dhabi",
    "place": "ANNEX",
    "address": "Abu Dhabi, UAE",
    "station": "없음",
    "photo_folder": "annex",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4535,
      "lng": 54.328
    },
    "gm_rating": 4.1,
    "gm_reviews": 193,
    "activity_rating": 4.1,
    "recommendation_score": 47,
    "overall_rank": 98,
    "category_rank": 18,
    "category_total": 18,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "art-central",
    "num": 14,
    "category": "culture",
    "area": "Al Reem Island",
    "place": "Art Central",
    "address": "Al Reem Island, Abu Dhabi",
    "station": "없음",
    "photo_folder": "art-central",
    "scores": {
      "photo": 5,
      "culture": 5,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 5,
      "solo": 5,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.4955,
      "lng": 54.4025
    },
    "gm_rating": 4.7,
    "gm_reviews": 164,
    "activity_rating": 4.7,
    "recommendation_score": 63,
    "overall_rank": 68,
    "category_rank": 11,
    "category_total": 13,
    "fame_stars": 3,
    "uniqueness": 3
  },
  {
    "id": "bait-gahwa",
    "num": 15,
    "category": "dining",
    "area": "Al Hosn",
    "place": "Bait Al Gahwa",
    "address": "Al Hosn, Abu Dhabi",
    "station": "Al Hosn",
    "photo_folder": "bait-gahwa",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4825,
      "lng": 54.3548
    },
    "gm_rating": 4.6,
    "gm_reviews": 219,
    "activity_rating": 4.17,
    "recommendation_score": 78,
    "overall_rank": 40,
    "category_rank": 3,
    "category_total": 18,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "bounce",
    "num": 16,
    "category": "themepark",
    "area": "Marina Mall",
    "place": "Bounce Abu Dhabi",
    "address": "Marina Mall, Abu Dhabi",
    "station": "Marina Mall",
    "photo_folder": "bounce",
    "scores": {
      "photo": 4,
      "culture": 2,
      "activity": 5,
      "relaxation": 2,
      "peaceful": 2,
      "couple": 3,
      "family": 5,
      "solo": 3,
      "tourist": 4,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.476,
      "lng": 54.322
    },
    "gm_rating": 4.4,
    "gm_reviews": 2354,
    "activity_rating": 4.4,
    "recommendation_score": 57,
    "overall_rank": 87,
    "category_rank": 28,
    "category_total": 28,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "breathe-wellness",
    "num": 17,
    "category": "beach",
    "area": "Saadiyat Island",
    "place": "Breathe Wellness Studio",
    "address": "Saadiyat Island, Abu Dhabi",
    "station": "없음",
    "photo_folder": "breathe-wellness",
    "scores": {
      "photo": 5,
      "culture": 2,
      "activity": 4,
      "relaxation": 5,
      "peaceful": 5,
      "couple": 5,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.5375,
      "lng": 54.434
    },
    "gm_rating": 4.7,
    "gm_reviews": 38,
    "activity_rating": 4.7,
    "recommendation_score": 53,
    "overall_rank": 93,
    "category_rank": 15,
    "category_total": 17,
    "fame_stars": 2,
    "uniqueness": 3
  },
  {
    "id": "cafe-del-mar",
    "num": 18,
    "category": "beach",
    "area": "Yas Bay",
    "place": "Cafe Del Mar",
    "address": "Yas Bay, Yas Island, Abu Dhabi",
    "station": "Yas Bay",
    "photo_folder": "cafe-del-mar",
    "scores": {
      "photo": 4,
      "culture": 4,
      "activity": 2,
      "relaxation": 5,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 5,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.465,
      "lng": 54.6085
    },
    "gm_rating": 4.7,
    "gm_reviews": 2931,
    "activity_rating": 4.7,
    "recommendation_score": 74,
    "overall_rank": 48,
    "category_rank": 6,
    "category_total": 17,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "capital-gate",
    "num": 19,
    "category": "landmark",
    "area": "ADNEC Area",
    "place": "Capital Gate Tower",
    "address": "ADNEC Area, Abu Dhabi",
    "station": "ADNEC",
    "photo_folder": "capital-gate",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4195,
      "lng": 54.4345
    },
    "gm_rating": 4.5,
    "gm_reviews": 3096,
    "activity_rating": 4.5,
    "recommendation_score": 47,
    "overall_rank": 99,
    "category_rank": 10,
    "category_total": 10,
    "fame_stars": 1,
    "uniqueness": 5
  },
  {
    "id": "central",
    "num": 20,
    "category": "dining",
    "area": "Yas Bay",
    "place": "Central",
    "address": "Yas Bay, Yas Island, Abu Dhabi",
    "station": "Yas Bay",
    "photo_folder": "central",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.465,
      "lng": 54.6085
    },
    "gm_rating": 4.1,
    "gm_reviews": 774,
    "activity_rating": 4.1,
    "recommendation_score": 60,
    "overall_rank": 77,
    "category_rank": 9,
    "category_total": 18,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "clay-studio",
    "num": 21,
    "category": "culture",
    "area": "Abu Dhabi",
    "place": "Clay Studio",
    "address": "Abu Dhabi, UAE",
    "station": "없음",
    "photo_folder": "clay-studio",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.47,
      "lng": 54.37
    },
    "gm_rating": 4.8,
    "gm_reviews": 86,
    "activity_rating": 4.8,
    "recommendation_score": 76,
    "overall_rank": 43,
    "category_rank": 7,
    "category_total": 13,
    "fame_stars": 2,
    "uniqueness": 4
  },
  {
    "id": "clymb-1",
    "num": 22,
    "category": "themepark",
    "area": "Yas Island",
    "place": "CLYMB Abu Dhabi",
    "address": "Yas Island, Abu Dhabi",
    "station": "Yas Mall",
    "photo_folder": "clymb-1",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4895,
      "lng": 54.6053
    },
    "gm_rating": 4.6,
    "gm_reviews": 908,
    "activity_rating": 4.88,
    "recommendation_score": 61,
    "overall_rank": 76,
    "category_rank": 26,
    "category_total": 28,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "clymb-2",
    "num": 23,
    "category": "themepark",
    "area": "Yas Island",
    "place": "CLYMB Abu Dhabi",
    "address": "Yas Island, Abu Dhabi",
    "station": "Yas Mall",
    "photo_folder": "clymb-2",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4895,
      "lng": 54.6053
    },
    "gm_rating": 4.6,
    "gm_reviews": 908,
    "activity_rating": 4.9,
    "recommendation_score": 60,
    "overall_rank": 80,
    "category_rank": 27,
    "category_total": 28,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "coya",
    "num": 24,
    "category": "dining",
    "area": "Al Maryah Island",
    "place": "Coya",
    "address": "Al Maryah Island, Abu Dhabi",
    "station": "없음",
    "photo_folder": "coya",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 2,
      "relaxation": 4,
      "peaceful": 3,
      "couple": 5,
      "family": 3,
      "solo": 3,
      "tourist": 4,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.5005,
      "lng": 54.394
    },
    "gm_rating": 4.6,
    "gm_reviews": 3078,
    "activity_rating": 4.6,
    "recommendation_score": 60,
    "overall_rank": 78,
    "category_rank": 10,
    "category_total": 18,
    "fame_stars": 1,
    "uniqueness": 4
  },
  {
    "id": "cultural-foundation",
    "num": 25,
    "category": "culture",
    "area": "Al Hosn",
    "place": "Cultural Foundation",
    "address": "Al Hosn, Abu Dhabi",
    "station": "Al Hosn",
    "photo_folder": "cultural-foundation",
    "scores": {
      "photo": 5,
      "culture": 5,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 5,
      "solo": 5,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.4825,
      "lng": 54.3548
    },
    "gm_rating": 4.7,
    "gm_reviews": 774,
    "activity_rating": 4.7,
    "recommendation_score": 81,
    "overall_rank": 36,
    "category_rank": 6,
    "category_total": 13,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "auto-museum",
    "num": 26,
    "category": "culture",
    "area": "Abu Dhabi - Al Ain Road",
    "place": "Emirates National Auto Museum",
    "address": "Abu Dhabi - Al Ain Road",
    "station": "없음",
    "photo_folder": "auto-museum",
    "scores": {
      "photo": 5,
      "culture": 5,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 5,
      "solo": 5,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.136,
      "lng": 55.1785
    },
    "gm_rating": 4.3,
    "gm_reviews": 1256,
    "activity_rating": 4.3,
    "recommendation_score": 56,
    "overall_rank": 88,
    "category_rank": 13,
    "category_total": 13,
    "fame_stars": 4,
    "uniqueness": 5
  },
  {
    "id": "emirates-kids",
    "num": 27,
    "category": "beach",
    "area": "Corniche",
    "place": "Emirates Palace",
    "address": "Corniche, Abu Dhabi",
    "station": "없음",
    "photo_folder": "emirates-kids",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4615,
      "lng": 54.317
    },
    "gm_rating": 4.8,
    "gm_reviews": 31134,
    "activity_rating": 4.77,
    "recommendation_score": 53,
    "overall_rank": 94,
    "category_rank": 16,
    "category_total": 17,
    "fame_stars": 1,
    "uniqueness": 4
  },
  {
    "id": "emirates-spa",
    "num": 28,
    "category": "beach",
    "area": "Corniche",
    "place": "Emirates Palace",
    "address": "Corniche, Abu Dhabi",
    "station": "없음",
    "photo_folder": "emirates-spa",
    "scores": {
      "photo": 5,
      "culture": 2,
      "activity": 4,
      "relaxation": 5,
      "peaceful": 5,
      "couple": 5,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4615,
      "lng": 54.317
    },
    "gm_rating": 4.8,
    "gm_reviews": 31134,
    "activity_rating": 4.89,
    "recommendation_score": 60,
    "overall_rank": 79,
    "category_rank": 14,
    "category_total": 17,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "emirates-cafe",
    "num": 29,
    "category": "dining",
    "area": "Corniche",
    "place": "Emirates Palace",
    "address": "Corniche, Abu Dhabi",
    "station": "없음",
    "photo_folder": "emirates-cafe",
    "scores": {
      "photo": 4,
      "culture": 4,
      "activity": 2,
      "relaxation": 5,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 5,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4615,
      "lng": 54.317
    },
    "gm_rating": 4.8,
    "gm_reviews": 31134,
    "activity_rating": 4.4,
    "recommendation_score": 58,
    "overall_rank": 83,
    "category_rank": 12,
    "category_total": 18,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "emirates-zoo",
    "num": 30,
    "category": "nature",
    "area": "Abu Dhabi - Al Ain Road",
    "place": "Emirates Park Zoo",
    "address": "Abu Dhabi - Al Ain Road",
    "station": "없음",
    "photo_folder": "emirates-zoo",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.1545,
      "lng": 55.128
    },
    "gm_rating": 4.4,
    "gm_reviews": 17884,
    "activity_rating": 4.4,
    "recommendation_score": 57,
    "overall_rank": 86,
    "category_rank": 4,
    "category_total": 4,
    "fame_stars": 5,
    "uniqueness": 3
  },
  {
    "id": "erth",
    "num": 31,
    "category": "culture",
    "area": "Abu Dhabi",
    "place": "Erth",
    "address": "Abu Dhabi, UAE",
    "station": "없음",
    "photo_folder": "erth",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.47,
      "lng": 54.37
    },
    "gm_rating": 4.6,
    "gm_reviews": 1247,
    "activity_rating": 4.6,
    "recommendation_score": 69,
    "overall_rank": 58,
    "category_rank": 9,
    "category_total": 13,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "etihad-arena",
    "num": 32,
    "category": "culture",
    "area": "Yas Bay",
    "place": "Etihad Arena",
    "address": "Yas Bay, Yas Island, Abu Dhabi",
    "station": "Yas Bay",
    "photo_folder": "etihad-arena",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.465,
      "lng": 54.6085
    },
    "gm_rating": 4.6,
    "gm_reviews": 3727,
    "activity_rating": 4.6,
    "recommendation_score": 71,
    "overall_rank": 52,
    "category_rank": 8,
    "category_total": 13,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "falcon-hospital",
    "num": 33,
    "category": "nature",
    "area": "Sweihan Road",
    "place": "Falcon Hospital",
    "address": "Sweihan Road, Abu Dhabi",
    "station": "없음",
    "photo_folder": "falcon-hospital",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4165,
      "lng": 54.598
    },
    "gm_rating": 4.3,
    "gm_reviews": 1840,
    "activity_rating": 4.3,
    "recommendation_score": 76,
    "overall_rank": 44,
    "category_rank": 1,
    "category_total": 4,
    "fame_stars": 4,
    "uniqueness": 5
  },
  {
    "id": "ferrari-1",
    "num": 34,
    "category": "themepark",
    "area": "Yas Island",
    "place": "Ferrari World Abu Dhabi",
    "address": "Yas Island, Abu Dhabi",
    "station": "Yas Mall",
    "photo_folder": "ferrari-1",
    "scores": {
      "photo": 5,
      "culture": 3,
      "activity": 5,
      "relaxation": 2,
      "peaceful": 1,
      "couple": 4,
      "family": 5,
      "solo": 3,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4844,
      "lng": 54.6073
    },
    "gm_rating": 4.5,
    "gm_reviews": 59200,
    "activity_rating": 4.07,
    "recommendation_score": 87,
    "overall_rank": 24,
    "category_rank": 10,
    "category_total": 28,
    "fame_stars": 2,
    "uniqueness": 5
  },
  {
    "id": "ferrari-2",
    "num": 35,
    "category": "themepark",
    "area": "Yas Island",
    "place": "Ferrari World Abu Dhabi",
    "address": "Yas Island, Abu Dhabi",
    "station": "Yas Mall",
    "photo_folder": "ferrari-2",
    "scores": {
      "photo": 5,
      "culture": 2,
      "activity": 5,
      "relaxation": 1,
      "peaceful": 1,
      "couple": 4,
      "family": 4,
      "solo": 3,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4844,
      "lng": 54.6073
    },
    "gm_rating": 4.5,
    "gm_reviews": 59200,
    "activity_rating": 3.12,
    "recommendation_score": 91,
    "overall_rank": 14,
    "category_rank": 3,
    "category_total": 28,
    "fame_stars": 3,
    "uniqueness": 5
  },
  {
    "id": "ferrari-3",
    "num": 36,
    "category": "themepark",
    "area": "Yas Island",
    "place": "Ferrari World Abu Dhabi",
    "address": "Yas Island, Abu Dhabi",
    "station": "Yas Mall",
    "photo_folder": "ferrari-3",
    "scores": {
      "photo": 4,
      "culture": 4,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 3,
      "couple": 4,
      "family": 5,
      "solo": 3,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4844,
      "lng": 54.6073
    },
    "gm_rating": 4.5,
    "gm_reviews": 59200,
    "activity_rating": 3.5,
    "recommendation_score": 92,
    "overall_rank": 13,
    "category_rank": 2,
    "category_total": 28,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "flamingo",
    "num": 37,
    "category": "dining",
    "area": "Al Maryah Island",
    "place": "Flamingo Collection",
    "address": "Al Maryah Island, Abu Dhabi",
    "station": "없음",
    "photo_folder": "flamingo",
    "scores": {
      "photo": 5,
      "culture": 2,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 3,
      "couple": 5,
      "family": 4,
      "solo": 3,
      "tourist": 4,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.5005,
      "lng": 54.394
    },
    "gm_rating": 4.7,
    "gm_reviews": 437,
    "activity_rating": 4.7,
    "recommendation_score": 83,
    "overall_rank": 29,
    "category_rank": 2,
    "category_total": 18,
    "fame_stars": 3,
    "uniqueness": 5
  },
  {
    "id": "fresh-basil",
    "num": 38,
    "category": "dining",
    "area": "Corniche",
    "place": "Fresh Basil",
    "address": "Corniche, Abu Dhabi",
    "station": "없음",
    "photo_folder": "fresh-basil",
    "scores": {
      "photo": 3,
      "culture": 2,
      "activity": 2,
      "relaxation": 5,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 5,
      "tourist": 4,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.4648,
      "lng": 54.3315
    },
    "gm_rating": 4.9,
    "gm_reviews": 112,
    "activity_rating": 4.9,
    "recommendation_score": 67,
    "overall_rank": 63,
    "category_rank": 5,
    "category_total": 18,
    "fame_stars": 3,
    "uniqueness": 3
  },
  {
    "id": "golden-dallah",
    "num": 39,
    "category": "culture",
    "area": "Various",
    "place": "Golden Dallah",
    "address": "Various Locations, Abu Dhabi",
    "station": "지점별 상이",
    "photo_folder": "golden-dallah",
    "scores": {
      "photo": 3,
      "culture": 5,
      "activity": 2,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 3,
      "family": 4,
      "solo": 5,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.47,
      "lng": 54.37
    },
    "gm_rating": 4.4,
    "gm_reviews": 501,
    "activity_rating": 4.4,
    "recommendation_score": 64,
    "overall_rank": 66,
    "category_rank": 7,
    "category_total": 18,
    "fame_stars": 1,
    "uniqueness": 4
  },
  {
    "id": "hakkasan",
    "num": 40,
    "category": "dining",
    "area": "Emirates Palace",
    "place": "Hakkasan",
    "address": "Emirates Palace, Abu Dhabi",
    "station": "없음",
    "photo_folder": "hakkasan",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 2,
      "relaxation": 4,
      "peaceful": 3,
      "couple": 5,
      "family": 3,
      "solo": 3,
      "tourist": 4,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.4615,
      "lng": 54.317
    },
    "gm_rating": 4.5,
    "gm_reviews": 1088,
    "activity_rating": 4.5,
    "recommendation_score": 59,
    "overall_rank": 81,
    "category_rank": 11,
    "category_total": 18,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "house-artisans",
    "num": 41,
    "category": "culture",
    "area": "Al Hosn",
    "place": "House of Artisans",
    "address": "Al Hosn, Abu Dhabi",
    "station": "Al Hosn",
    "photo_folder": "house-artisans",
    "scores": {
      "photo": 4,
      "culture": 5,
      "activity": 4,
      "relaxation": 3,
      "peaceful": 4,
      "couple": 3,
      "family": 5,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4825,
      "lng": 54.3548
    },
    "gm_rating": 4.6,
    "gm_reviews": 219,
    "activity_rating": 4.33,
    "recommendation_score": 88,
    "overall_rank": 20,
    "category_rank": 5,
    "category_total": 13,
    "fame_stars": 1,
    "uniqueness": 4
  },
  {
    "id": "hudayriyat",
    "num": 42,
    "category": "beach",
    "area": "Hudayriyat Island",
    "place": "Hudayriyat Island",
    "address": "Hudayriyat Island, Abu Dhabi",
    "station": "없음",
    "photo_folder": "hudayriyat",
    "scores": {
      "photo": 5,
      "culture": 2,
      "activity": 5,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 5,
      "solo": 4,
      "tourist": 4,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4245,
      "lng": 54.452
    },
    "gm_rating": 4.6,
    "gm_reviews": 1991,
    "activity_rating": 4.6,
    "recommendation_score": 70,
    "overall_rank": 55,
    "category_rank": 9,
    "category_total": 17,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "jumeirah-saadiyat",
    "num": 43,
    "category": "beach",
    "area": "Saadiyat Island",
    "place": "Jumeirah Saadiyat",
    "address": "Saadiyat Island, Abu Dhabi",
    "station": "없음",
    "photo_folder": "jumeirah-saadiyat",
    "scores": {
      "photo": 5,
      "culture": 3,
      "activity": 4,
      "relaxation": 5,
      "peaceful": 5,
      "couple": 5,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.542,
      "lng": 54.4325
    },
    "gm_rating": 4.6,
    "gm_reviews": 3172,
    "activity_rating": 4.6,
    "recommendation_score": 70,
    "overall_rank": 54,
    "category_rank": 8,
    "category_total": 17,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "la-cava",
    "num": 44,
    "category": "dining",
    "area": "Al Maryah Island",
    "place": "La Cava",
    "address": "Al Maryah Island, Abu Dhabi",
    "station": "없음",
    "photo_folder": "la-cava",
    "scores": {
      "photo": 3,
      "culture": 3,
      "activity": 2,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 5,
      "family": 2,
      "solo": 4,
      "tourist": 4,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.502,
      "lng": 54.393
    },
    "gm_rating": 4.5,
    "gm_reviews": 134,
    "activity_rating": 4.5,
    "recommendation_score": 57,
    "overall_rank": 85,
    "category_rank": 13,
    "category_total": 18,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "louvre-1",
    "num": 45,
    "category": "culture",
    "area": "Saadiyat Island",
    "place": "Louvre Abu Dhabi",
    "address": "Saadiyat Island, Abu Dhabi",
    "station": "없음",
    "photo_folder": "louvre-1",
    "scores": {
      "photo": 5,
      "culture": 5,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 5,
      "solo": 5,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.5337,
      "lng": 54.3982
    },
    "gm_rating": 4.7,
    "gm_reviews": 37545,
    "activity_rating": 4.59,
    "recommendation_score": 97,
    "overall_rank": 5,
    "category_rank": 1,
    "category_total": 13,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "louvre-2",
    "num": 46,
    "category": "culture",
    "area": "Saadiyat Island",
    "place": "Louvre Abu Dhabi",
    "address": "Saadiyat Island, Abu Dhabi",
    "station": "없음",
    "photo_folder": "louvre-2",
    "scores": {
      "photo": 5,
      "culture": 5,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 5,
      "solo": 5,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.5337,
      "lng": 54.3982
    },
    "gm_rating": 4.7,
    "gm_reviews": 37545,
    "activity_rating": 4.48,
    "recommendation_score": 96,
    "overall_rank": 6,
    "category_rank": 2,
    "category_total": 13,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "louvre-3",
    "num": 47,
    "category": "culture",
    "area": "Saadiyat Island",
    "place": "Louvre Abu Dhabi",
    "address": "Saadiyat Island, Abu Dhabi",
    "station": "없음",
    "photo_folder": "louvre-3",
    "scores": {
      "photo": 5,
      "culture": 5,
      "activity": 4,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 5,
      "solo": 5,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.5337,
      "lng": 54.3982
    },
    "gm_rating": 4.7,
    "gm_reviews": 37545,
    "activity_rating": 4.59,
    "recommendation_score": 96,
    "overall_rank": 7,
    "category_rank": 3,
    "category_total": 13,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "louvre-4",
    "num": 48,
    "category": "culture",
    "area": "Saadiyat Island",
    "place": "Louvre Abu Dhabi",
    "address": "Saadiyat Island, Abu Dhabi",
    "station": "없음",
    "photo_folder": "louvre-4",
    "scores": {
      "photo": 5,
      "culture": 4,
      "activity": 5,
      "relaxation": 5,
      "peaceful": 5,
      "couple": 5,
      "family": 4,
      "solo": 5,
      "tourist": 5,
      "accessibility": 3
    },
    "coordinates": {
      "lat": 24.5337,
      "lng": 54.3982
    },
    "gm_rating": 4.7,
    "gm_reviews": 37564,
    "activity_rating": 4.62,
    "recommendation_score": 96,
    "overall_rank": 8,
    "category_rank": 4,
    "category_total": 13,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "gold-souk",
    "num": 49,
    "category": "culture",
    "area": "Madinat Zayed",
    "place": "Madinat Zayed Gold Souk",
    "address": "Madinat Zayed, Abu Dhabi",
    "station": "없음",
    "photo_folder": "gold-souk",
    "scores": {
      "photo": 3,
      "culture": 4,
      "activity": 3,
      "relaxation": 2,
      "peaceful": 2,
      "couple": 3,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 3
    },
    "coordinates": {
      "lat": 24.468,
      "lng": 54.3538
    },
    "gm_rating": 4.4,
    "gm_reviews": 5085,
    "activity_rating": 4.4,
    "recommendation_score": 54,
    "overall_rank": 92,
    "category_rank": 9,
    "category_total": 10,
    "fame_stars": 1,
    "uniqueness": 3
  },
  {
    "id": "mamsha",
    "num": 50,
    "category": "beach",
    "area": "Saadiyat Island",
    "place": "Mamsha Al Saadiyat",
    "address": "Saadiyat Island, Abu Dhabi",
    "station": "없음",
    "photo_folder": "mamsha",
    "scores": {
      "photo": 5,
      "culture": 3,
      "activity": 4,
      "relaxation": 5,
      "peaceful": 5,
      "couple": 5,
      "family": 5,
      "solo": 5,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.5395,
      "lng": 54.4285
    },
    "gm_rating": 4.6,
    "gm_reviews": 1666,
    "activity_rating": 4.6,
    "recommendation_score": 61,
    "overall_rank": 75,
    "category_rank": 13,
    "category_total": 17,
    "fame_stars": 4,
    "uniqueness": 3
  },
  {
    "id": "manarat",
    "num": 51,
    "category": "culture",
    "area": "Saadiyat Island",
    "place": "Manarat Al Saadiyat",
    "address": "Saadiyat Island, Abu Dhabi",
    "station": "없음",
    "photo_folder": "manarat",
    "scores": {
      "photo": 4,
      "culture": 5,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 5,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.539,
      "lng": 54.4325
    },
    "gm_rating": 4.5,
    "gm_reviews": 3215,
    "activity_rating": 4.5,
    "recommendation_score": 59,
    "overall_rank": 82,
    "category_rank": 12,
    "category_total": 13,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "mezlai",
    "num": 52,
    "category": "culture",
    "area": "Emirates Palace",
    "place": "Mezlai",
    "address": "Emirates Palace, Abu Dhabi",
    "station": "없음",
    "photo_folder": "mezlai",
    "scores": {
      "photo": 3,
      "culture": 5,
      "activity": 2,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4615,
      "lng": 54.317
    },
    "gm_rating": 4.4,
    "gm_reviews": 123,
    "activity_rating": 4.4,
    "recommendation_score": 55,
    "overall_rank": 90,
    "category_rank": 14,
    "category_total": 18,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "nat-geo",
    "num": 53,
    "category": "themepark",
    "area": "Al Maryah Island",
    "place": "National Geographic Ultimate Explorer",
    "address": "Al Maryah Island, Abu Dhabi",
    "station": "없음",
    "photo_folder": "nat-geo",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 4,
      "relaxation": 3,
      "peaceful": 2,
      "couple": 3,
      "family": 5,
      "solo": 3,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.5005,
      "lng": 54.394
    },
    "gm_rating": 4.4,
    "gm_reviews": 250,
    "activity_rating": 4.4,
    "recommendation_score": 77,
    "overall_rank": 42,
    "category_rank": 19,
    "category_total": 28,
    "fame_stars": 3,
    "uniqueness": 5
  },
  {
    "id": "observation-deck",
    "num": 54,
    "category": "landmark",
    "area": "Corniche",
    "place": "Observation Deck at 300",
    "address": "Corniche, Abu Dhabi",
    "station": "없음",
    "photo_folder": "observation-deck",
    "scores": {
      "photo": 5,
      "culture": 2,
      "activity": 2,
      "relaxation": 5,
      "peaceful": 5,
      "couple": 5,
      "family": 4,
      "solo": 5,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4615,
      "lng": 54.3298
    },
    "gm_rating": 4.7,
    "gm_reviews": 2971,
    "activity_rating": 4.7,
    "recommendation_score": 74,
    "overall_rank": 49,
    "category_rank": 6,
    "category_total": 10,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "pixoul",
    "num": 55,
    "category": "themepark",
    "area": "Al Qana",
    "place": "Pixoul",
    "address": "Al Qana, Abu Dhabi",
    "station": "없음",
    "photo_folder": "pixoul",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4015,
      "lng": 54.4985
    },
    "gm_rating": 4.5,
    "gm_reviews": 579,
    "activity_rating": 4.5,
    "recommendation_score": 76,
    "overall_rank": 45,
    "category_rank": 20,
    "category_total": 28,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "prison-island",
    "num": 56,
    "category": "themepark",
    "area": "Tourist Club Area",
    "place": "Prison Island",
    "address": "Abu Dhabi Mall, Abu Dhabi",
    "station": "Abu Dhabi Mall",
    "photo_folder": "prison-island",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.496,
      "lng": 54.3833
    },
    "gm_rating": 4.9,
    "gm_reviews": 2384,
    "activity_rating": 4.9,
    "recommendation_score": 79,
    "overall_rank": 39,
    "category_rank": 18,
    "category_total": 28,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "qasr-al-hosn",
    "num": 57,
    "category": "landmark",
    "area": "Al Hosn",
    "place": "Qasr Al Hosn",
    "address": "Al Hosn, Abu Dhabi",
    "station": "Al Hosn",
    "photo_folder": "qasr-al-hosn",
    "scores": {
      "photo": 5,
      "culture": 5,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 5,
      "solo": 5,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.4825,
      "lng": 54.3548
    },
    "gm_rating": 4.6,
    "gm_reviews": 7515,
    "activity_rating": 4.6,
    "recommendation_score": 79,
    "overall_rank": 38,
    "category_rank": 5,
    "category_total": 10,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "qasr-al-muwaiji",
    "num": 58,
    "category": "landmark",
    "area": "Al Ain",
    "place": "Qasr Al Muwaiji",
    "address": "Al Ain, Abu Dhabi",
    "station": "없음",
    "photo_folder": "qasr-al-muwaiji",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.2145,
      "lng": 55.7584
    },
    "gm_rating": 4.6,
    "gm_reviews": 1347,
    "activity_rating": 4.6,
    "recommendation_score": 62,
    "overall_rank": 72,
    "category_rank": 8,
    "category_total": 10,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "qasr-sarab",
    "num": 59,
    "category": "beach",
    "area": "Liwa Desert",
    "place": "Qasr Al Sarab",
    "address": "Liwa Desert, Abu Dhabi",
    "station": "없음",
    "photo_folder": "qasr-sarab",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 23.1005,
      "lng": 53.7645
    },
    "gm_rating": 4.7,
    "gm_reviews": 3183,
    "activity_rating": 4.7,
    "recommendation_score": 79,
    "overall_rank": 37,
    "category_rank": 4,
    "category_total": 17,
    "fame_stars": 4,
    "uniqueness": 5
  },
  {
    "id": "qasr-al-watan-1",
    "num": 60,
    "category": "landmark",
    "area": "Presidential Palace",
    "place": "Qasr Al Watan",
    "address": "Presidential Palace, Abu Dhabi",
    "station": "없음",
    "photo_folder": "qasr-al-watan-1",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4625,
      "lng": 54.3055
    },
    "gm_rating": 4.8,
    "gm_reviews": 9980,
    "activity_rating": 4.48,
    "recommendation_score": 96,
    "overall_rank": 9,
    "category_rank": 3,
    "category_total": 10,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "qasr-al-watan-2",
    "num": 61,
    "category": "landmark",
    "area": "Presidential Palace",
    "place": "Qasr Al Watan",
    "address": "Presidential Palace, Abu Dhabi",
    "station": "없음",
    "photo_folder": "qasr-al-watan-2",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4625,
      "lng": 54.3055
    },
    "gm_rating": 4.8,
    "gm_reviews": 9982,
    "activity_rating": 4.91,
    "recommendation_score": 96,
    "overall_rank": 10,
    "category_rank": 4,
    "category_total": 10,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "rays-grill",
    "num": 62,
    "category": "dining",
    "area": "Corniche",
    "place": "Rays Grill",
    "address": "Corniche, Abu Dhabi",
    "station": "없음",
    "photo_folder": "rays-grill",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4615,
      "lng": 54.3298
    },
    "gm_rating": 4.5,
    "gm_reviews": 340,
    "activity_rating": 4.5,
    "recommendation_score": 66,
    "overall_rank": 64,
    "category_rank": 6,
    "category_total": 18,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "reem-mall",
    "num": 63,
    "category": "shopping",
    "area": "Reem Island",
    "place": "Reem Mall",
    "address": "Reem Island, Abu Dhabi",
    "station": "Reem Island",
    "photo_folder": "reem-mall",
    "scores": {
      "photo": 3,
      "culture": 3,
      "activity": 3,
      "relaxation": 3,
      "peaceful": 2,
      "couple": 4,
      "family": 5,
      "solo": 4,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.4975,
      "lng": 54.4095
    },
    "gm_rating": 4.6,
    "gm_reviews": 4707,
    "activity_rating": 4.6,
    "recommendation_score": 64,
    "overall_rank": 67,
    "category_rank": 4,
    "category_total": 4,
    "fame_stars": 1,
    "uniqueness": 4
  },
  {
    "id": "rixos-marina",
    "num": 64,
    "category": "beach",
    "area": "Al Bateen",
    "place": "Rixos Marina",
    "address": "Al Bateen, Abu Dhabi",
    "station": "없음",
    "photo_folder": "rixos-marina",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4585,
      "lng": 54.3395
    },
    "gm_rating": 4.8,
    "gm_reviews": 7950,
    "activity_rating": 4.8,
    "recommendation_score": 87,
    "overall_rank": 22,
    "category_rank": 1,
    "category_total": 17,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "rixos-saadiyat",
    "num": 65,
    "category": "beach",
    "area": "Saadiyat Island",
    "place": "Rixos Premium Saadiyat",
    "address": "Saadiyat Island, Abu Dhabi",
    "station": "Saadiyat Island",
    "photo_folder": "rixos-saadiyat",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.548,
      "lng": 54.4185
    },
    "gm_rating": 4.7,
    "gm_reviews": 5432,
    "activity_rating": 4.7,
    "recommendation_score": 83,
    "overall_rank": 31,
    "category_rank": 3,
    "category_total": 17,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "saadiyat-beach-club",
    "num": 66,
    "category": "beach",
    "area": "Saadiyat Island",
    "place": "Saadiyat Beach Club",
    "address": "Saadiyat Island, Abu Dhabi",
    "station": "Saadiyat Island",
    "photo_folder": "saadiyat-beach-club",
    "scores": {
      "photo": 5,
      "culture": 2,
      "activity": 4,
      "relaxation": 5,
      "peaceful": 5,
      "couple": 5,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.5415,
      "lng": 54.4275
    },
    "gm_rating": 4.5,
    "gm_reviews": 3576,
    "activity_rating": 4.5,
    "recommendation_score": 41,
    "overall_rank": 100,
    "category_rank": 17,
    "category_total": 17,
    "fame_stars": 3,
    "uniqueness": 3
  },
  {
    "id": "seaworld-1",
    "num": 67,
    "category": "themepark",
    "area": "Yas Island",
    "place": "SeaWorld Yas Island",
    "address": "Yas Island, Abu Dhabi",
    "station": "Yas Island",
    "photo_folder": "seaworld-1",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4885,
      "lng": 54.602
    },
    "gm_rating": 4.7,
    "gm_reviews": 13307,
    "activity_rating": 4.34,
    "recommendation_score": 87,
    "overall_rank": 25,
    "category_rank": 11,
    "category_total": 28,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "seaworld-2",
    "num": 68,
    "category": "themepark",
    "area": "Yas Island",
    "place": "SeaWorld Yas Island",
    "address": "Yas Island, Abu Dhabi",
    "station": "Yas Island",
    "photo_folder": "seaworld-2",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4885,
      "lng": 54.602
    },
    "gm_rating": 4.7,
    "gm_reviews": 13307,
    "activity_rating": 4.21,
    "recommendation_score": 87,
    "overall_rank": 26,
    "category_rank": 12,
    "category_total": 28,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "seaworld-3",
    "num": 69,
    "category": "themepark",
    "area": "Yas Island",
    "place": "SeaWorld Yas Island",
    "address": "Yas Island, Abu Dhabi",
    "station": "Yas Island",
    "photo_folder": "seaworld-3",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4885,
      "lng": 54.602
    },
    "gm_rating": 4.7,
    "gm_reviews": 13307,
    "activity_rating": 4.7,
    "recommendation_score": 86,
    "overall_rank": 28,
    "category_rank": 14,
    "category_total": 28,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "shangrila",
    "num": 70,
    "category": "beach",
    "area": "Between Two Bridges",
    "place": "Shangri-La Hotel",
    "address": "Between Two Bridges, Abu Dhabi",
    "station": "없음",
    "photo_folder": "shangrila",
    "scores": {
      "photo": 5,
      "culture": 3,
      "activity": 3,
      "relaxation": 5,
      "peaceful": 5,
      "couple": 5,
      "family": 4,
      "solo": 5,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.42,
      "lng": 54.4665
    },
    "gm_rating": 4.6,
    "gm_reviews": 7902,
    "activity_rating": 4.6,
    "recommendation_score": 62,
    "overall_rank": 71,
    "category_rank": 12,
    "category_total": 17,
    "fame_stars": 4,
    "uniqueness": 3
  },
  {
    "id": "mosque-1",
    "num": 71,
    "category": "landmark",
    "area": "Grand Mosque",
    "place": "Sheikh Zayed Grand Mosque",
    "address": "Grand Mosque, Abu Dhabi",
    "station": "Grand Mosque",
    "photo_folder": "mosque-1",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4128,
      "lng": 54.4745
    },
    "gm_rating": 4.8,
    "gm_reviews": 59694,
    "activity_rating": 4.57,
    "recommendation_score": 99,
    "overall_rank": 2,
    "category_rank": 1,
    "category_total": 10,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "mosque-2",
    "num": 72,
    "category": "landmark",
    "area": "Grand Mosque",
    "place": "Sheikh Zayed Grand Mosque",
    "address": "Grand Mosque, Abu Dhabi",
    "station": "Grand Mosque",
    "photo_folder": "mosque-2",
    "scores": {
      "photo": 5,
      "culture": 5,
      "activity": 2,
      "relaxation": 5,
      "peaceful": 5,
      "couple": 4,
      "family": 5,
      "solo": 5,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.4128,
      "lng": 54.4745
    },
    "gm_rating": 4.8,
    "gm_reviews": 59694,
    "activity_rating": 4.77,
    "recommendation_score": 99,
    "overall_rank": 3,
    "category_rank": 2,
    "category_total": 10,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "sir-bani-yas",
    "num": 73,
    "category": "nature",
    "area": "Sir Bani Yas Island",
    "place": "Sir Bani Yas Island",
    "address": "Sir Bani Yas Island, Abu Dhabi",
    "station": "없음",
    "photo_folder": "sir-bani-yas",
    "scores": {
      "photo": 5,
      "culture": 3,
      "activity": 5,
      "relaxation": 5,
      "peaceful": 5,
      "couple": 5,
      "family": 5,
      "solo": 4,
      "tourist": 4,
      "accessibility": 3
    },
    "coordinates": {
      "lat": 24.3165,
      "lng": 52.575
    },
    "gm_rating": 4.5,
    "gm_reviews": 887,
    "activity_rating": 4.5,
    "recommendation_score": 68,
    "overall_rank": 59,
    "category_rank": 3,
    "category_total": 4,
    "fame_stars": 3,
    "uniqueness": 5
  },
  {
    "id": "snow-1",
    "num": 74,
    "category": "themepark",
    "area": "Reem Island",
    "place": "Snow Abu Dhabi",
    "address": "Reem Mall, Reem Island, Abu Dhabi",
    "station": "Reem Mall",
    "photo_folder": "snow-1",
    "scores": {
      "photo": 4,
      "culture": 1,
      "activity": 5,
      "relaxation": 2,
      "peaceful": 1,
      "couple": 3,
      "family": 5,
      "solo": 3,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4975,
      "lng": 54.4095
    },
    "gm_rating": 4.2,
    "gm_reviews": 1269,
    "activity_rating": 3.92,
    "recommendation_score": 63,
    "overall_rank": 69,
    "category_rank": 23,
    "category_total": 28,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "snow-2",
    "num": 75,
    "category": "themepark",
    "area": "Reem Island",
    "place": "Snow Abu Dhabi",
    "address": "Reem Mall, Reem Island, Abu Dhabi",
    "station": "Reem Mall",
    "photo_folder": "snow-2",
    "scores": {
      "photo": 4,
      "culture": 1,
      "activity": 5,
      "relaxation": 2,
      "peaceful": 1,
      "couple": 4,
      "family": 5,
      "solo": 3,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4975,
      "lng": 54.4095
    },
    "gm_rating": 4.2,
    "gm_reviews": 1269,
    "activity_rating": 4.5,
    "recommendation_score": 63,
    "overall_rank": 70,
    "category_rank": 24,
    "category_total": 28,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "snow-3",
    "num": 76,
    "category": "themepark",
    "area": "Reem Island",
    "place": "Snow Abu Dhabi",
    "address": "Reem Mall, Reem Island, Abu Dhabi",
    "station": "Reem Mall",
    "photo_folder": "snow-3",
    "scores": {
      "photo": 5,
      "culture": 1,
      "activity": 5,
      "relaxation": 2,
      "peaceful": 1,
      "couple": 4,
      "family": 5,
      "solo": 3,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4975,
      "lng": 54.4095
    },
    "gm_rating": 4.2,
    "gm_reviews": 1270,
    "activity_rating": 3.67,
    "recommendation_score": 62,
    "overall_rank": 73,
    "category_rank": 25,
    "category_total": 28,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "st-regis",
    "num": 77,
    "category": "beach",
    "area": "Saadiyat Island",
    "place": "St. Regis Saadiyat",
    "address": "Saadiyat Island, Abu Dhabi",
    "station": "Saadiyat Island",
    "photo_folder": "st-regis",
    "scores": {
      "photo": 5,
      "culture": 2,
      "activity": 3,
      "relaxation": 5,
      "peaceful": 5,
      "couple": 5,
      "family": 4,
      "solo": 5,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.5435,
      "lng": 54.4315
    },
    "gm_rating": 4.7,
    "gm_reviews": 4396,
    "activity_rating": 4.7,
    "recommendation_score": 75,
    "overall_rank": 46,
    "category_rank": 5,
    "category_total": 17,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "surf-abudhabi",
    "num": 78,
    "category": "adventure",
    "area": "Hudayriyat Island",
    "place": "Surf Abu Dhabi",
    "address": "Hudayriyat Island, Abu Dhabi",
    "station": "Hudayriyat Island",
    "photo_folder": "surf-abudhabi",
    "scores": {
      "photo": 5,
      "culture": 2,
      "activity": 5,
      "relaxation": 3,
      "peaceful": 3,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4245,
      "lng": 54.452
    },
    "gm_rating": 4.7,
    "gm_reviews": 227,
    "activity_rating": 4.7,
    "recommendation_score": 73,
    "overall_rank": 50,
    "category_rank": 7,
    "category_total": 17,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "the-bridge",
    "num": 79,
    "category": "adventure",
    "area": "Al Qana",
    "place": "The Bridge",
    "address": "Al Qana, Abu Dhabi",
    "station": "Maryah Island",
    "photo_folder": "the-bridge",
    "scores": {
      "photo": 3,
      "culture": 2,
      "activity": 4,
      "relaxation": 3,
      "peaceful": 2,
      "couple": 3,
      "family": 4,
      "solo": 3,
      "tourist": 4,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4015,
      "lng": 54.4985
    },
    "gm_rating": 4.8,
    "gm_reviews": 2501,
    "activity_rating": 4.8,
    "recommendation_score": 87,
    "overall_rank": 23,
    "category_rank": 2,
    "category_total": 17,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "galleria-1",
    "num": 80,
    "category": "shopping",
    "area": "Al Maryah Island",
    "place": "The Galleria",
    "address": "Al Maryah Island, Abu Dhabi",
    "station": "Maryah Island",
    "photo_folder": "galleria-1",
    "scores": {
      "photo": 3,
      "culture": 2,
      "activity": 3,
      "relaxation": 3,
      "peaceful": 3,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.5005,
      "lng": 54.394
    },
    "gm_rating": 4.6,
    "gm_reviews": 20663,
    "activity_rating": 4.68,
    "recommendation_score": 83,
    "overall_rank": 30,
    "category_rank": 2,
    "category_total": 4,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "galleria-2",
    "num": 81,
    "category": "shopping",
    "area": "Al Maryah Island",
    "place": "The Galleria",
    "address": "Al Maryah Island, Abu Dhabi",
    "station": "Maryah Island",
    "photo_folder": "galleria-2",
    "scores": {
      "photo": 3,
      "culture": 2,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 3,
      "couple": 4,
      "family": 4,
      "solo": 5,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.5005,
      "lng": 54.394
    },
    "gm_rating": 4.6,
    "gm_reviews": 20664,
    "activity_rating": 4.6,
    "recommendation_score": 82,
    "overall_rank": 34,
    "category_rank": 3,
    "category_total": 4,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "aquarium-1",
    "num": 82,
    "category": "themepark",
    "area": "Al Qana",
    "place": "The National Aquarium",
    "address": "Al Qana, Abu Dhabi",
    "station": "Al Qana",
    "photo_folder": "aquarium-1",
    "scores": {
      "photo": 5,
      "culture": 2,
      "activity": 3,
      "relaxation": 4,
      "peaceful": 4,
      "couple": 4,
      "family": 5,
      "solo": 4,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.4015,
      "lng": 54.4985
    },
    "gm_rating": 4.7,
    "gm_reviews": 5328,
    "activity_rating": 4.75,
    "recommendation_score": 83,
    "overall_rank": 32,
    "category_rank": 15,
    "category_total": 28,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "aquarium-2",
    "num": 83,
    "category": "themepark",
    "area": "Al Qana",
    "place": "The National Aquarium",
    "address": "Al Qana, Abu Dhabi",
    "station": "Al Qana",
    "photo_folder": "aquarium-2",
    "scores": {
      "photo": 4,
      "culture": 2,
      "activity": 4,
      "relaxation": 3,
      "peaceful": 3,
      "couple": 4,
      "family": 5,
      "solo": 3,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.4015,
      "lng": 54.4985
    },
    "gm_rating": 4.7,
    "gm_reviews": 5330,
    "activity_rating": 4.75,
    "recommendation_score": 82,
    "overall_rank": 35,
    "category_rank": 17,
    "category_total": 28,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "ufc-gym",
    "num": 84,
    "category": "adventure",
    "area": "Maqtaa",
    "place": "UFC Gym",
    "address": "Maqtaa Mall, Abu Dhabi",
    "station": "Yas Mall",
    "photo_folder": "ufc-gym",
    "scores": {
      "photo": 2,
      "culture": 1,
      "activity": 5,
      "relaxation": 2,
      "peaceful": 2,
      "couple": 3,
      "family": 3,
      "solo": 5,
      "tourist": 3,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4185,
      "lng": 54.4585
    },
    "gm_rating": 4.4,
    "gm_reviews": 293,
    "activity_rating": 4.4,
    "recommendation_score": 40,
    "overall_rank": 101,
    "category_rank": 7,
    "category_total": 7,
    "fame_stars": 3,
    "uniqueness": 2
  },
  {
    "id": "wahat-al-karama",
    "num": 85,
    "category": "culture",
    "area": "Grand Mosque Area",
    "place": "Wahat Al Karama",
    "address": "Grand Mosque Area, Abu Dhabi",
    "station": "Grand Mosque",
    "photo_folder": "wahat-al-karama",
    "scores": {
      "photo": 5,
      "culture": 5,
      "activity": 2,
      "relaxation": 4,
      "peaceful": 5,
      "couple": 4,
      "family": 4,
      "solo": 5,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.4178,
      "lng": 54.4685
    },
    "gm_rating": 4.7,
    "gm_reviews": 2146,
    "activity_rating": 4.7,
    "recommendation_score": 72,
    "overall_rank": 51,
    "category_rank": 7,
    "category_total": 10,
    "fame_stars": 1,
    "uniqueness": 4
  },
  {
    "id": "warner-1",
    "num": 86,
    "category": "themepark",
    "area": "Yas Island",
    "place": "Warner Bros. World",
    "address": "Yas Island, Abu Dhabi",
    "station": "Yas Mall",
    "photo_folder": "warner-1",
    "scores": {
      "photo": 5,
      "culture": 2,
      "activity": 5,
      "relaxation": 1,
      "peaceful": 1,
      "couple": 3,
      "family": 5,
      "solo": 3,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4835,
      "lng": 54.6095
    },
    "gm_rating": 4.5,
    "gm_reviews": 22763,
    "activity_rating": 4.79,
    "recommendation_score": 71,
    "overall_rank": 53,
    "category_rank": 21,
    "category_total": 28,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "warner-2",
    "num": 87,
    "category": "themepark",
    "area": "Yas Island",
    "place": "Warner Bros. World",
    "address": "Yas Island, Abu Dhabi",
    "station": "Yas Mall",
    "photo_folder": "warner-2",
    "scores": {
      "photo": 5,
      "culture": 2,
      "activity": 5,
      "relaxation": 2,
      "peaceful": 1,
      "couple": 4,
      "family": 5,
      "solo": 3,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4835,
      "lng": 54.6095
    },
    "gm_rating": 4.5,
    "gm_reviews": 22774,
    "activity_rating": 3.78,
    "recommendation_score": 83,
    "overall_rank": 33,
    "category_rank": 16,
    "category_total": 28,
    "fame_stars": 2,
    "uniqueness": 5
  },
  {
    "id": "white",
    "num": 88,
    "category": "dining",
    "area": "Yas Bay",
    "place": "White",
    "address": "Yas Bay, Yas Island, Abu Dhabi",
    "station": "Yas Island",
    "photo_folder": "white",
    "scores": {
      "photo": 5,
      "culture": 2,
      "activity": 4,
      "relaxation": 5,
      "peaceful": 4,
      "couple": 5,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.465,
      "lng": 54.6085
    },
    "gm_rating": 3.5,
    "gm_reviews": 326,
    "activity_rating": 3.5,
    "recommendation_score": 55,
    "overall_rank": 91,
    "category_rank": 15,
    "category_total": 18,
    "fame_stars": 3,
    "uniqueness": 4
  },
  {
    "id": "wtc-mall",
    "num": 89,
    "category": "themepark",
    "area": "Central Abu Dhabi",
    "place": "World Trade Center Mall",
    "address": "Central Abu Dhabi",
    "station": "없음",
    "photo_folder": "wtc-mall",
    "scores": {
      "photo": 3,
      "culture": 2,
      "activity": 3,
      "relaxation": 3,
      "peaceful": 2,
      "couple": 4,
      "family": 5,
      "solo": 4,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.488,
      "lng": 54.3658
    },
    "gm_rating": 4.4,
    "gm_reviews": 11761,
    "activity_rating": 4.4,
    "recommendation_score": 68,
    "overall_rank": 62,
    "category_rank": 22,
    "category_total": 28,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "xtreme-zone",
    "num": 90,
    "category": "themepark",
    "area": "Al Maryah Island",
    "place": "Xtreme Zone",
    "address": "Al Maryah Island, Abu Dhabi",
    "station": "Yas Mall",
    "photo_folder": "xtreme-zone",
    "scores": {
      "photo": 3,
      "culture": 1,
      "activity": 5,
      "relaxation": 1,
      "peaceful": 1,
      "couple": 3,
      "family": 5,
      "solo": 3,
      "tourist": 4,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.5005,
      "lng": 54.394
    },
    "gm_rating": 4.5,
    "gm_reviews": 526,
    "activity_rating": 4.5,
    "recommendation_score": 87,
    "overall_rank": 27,
    "category_rank": 13,
    "category_total": 28,
    "fame_stars": 3,
    "uniqueness": 5
  },
  {
    "id": "yas-mall-challenge",
    "num": 91,
    "category": "adventure",
    "area": "Yas Island",
    "place": "Yas Mall",
    "address": "Yas Mall, Yas Island, Abu Dhabi",
    "station": "Yas Mall",
    "photo_folder": "yas-mall-challenge",
    "scores": {
      "photo": 3,
      "culture": 3,
      "activity": 3,
      "relaxation": 3,
      "peaceful": 2,
      "couple": 4,
      "family": 5,
      "solo": 4,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.4881,
      "lng": 54.6074
    },
    "gm_rating": 4.6,
    "gm_reviews": 44633,
    "activity_rating": 4.6,
    "recommendation_score": 93,
    "overall_rank": 12,
    "category_rank": 1,
    "category_total": 7,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "yas-mall",
    "num": 92,
    "category": "shopping",
    "area": "Yas Island",
    "place": "Yas Mall",
    "address": "Yas Mall, Yas Island, Abu Dhabi",
    "station": "Yas Mall",
    "photo_folder": "yas-mall",
    "scores": {
      "photo": 3,
      "culture": 3,
      "activity": 3,
      "relaxation": 3,
      "peaceful": 2,
      "couple": 4,
      "family": 5,
      "solo": 4,
      "tourist": 5,
      "accessibility": 5
    },
    "coordinates": {
      "lat": 24.4881,
      "lng": 54.6074
    },
    "gm_rating": 4.6,
    "gm_reviews": 44639,
    "activity_rating": 4.52,
    "recommendation_score": 93,
    "overall_rank": 11,
    "category_rank": 1,
    "category_total": 4,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "yas-marina-1",
    "num": 93,
    "category": "adventure",
    "area": "Yas Island",
    "place": "Yas Marina Circuit",
    "address": "Yas Marina Circuit, Yas Island",
    "station": "Yas Marina",
    "photo_folder": "yas-marina-1",
    "scores": {
      "photo": 5,
      "culture": 3,
      "activity": 5,
      "relaxation": 2,
      "peaceful": 2,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4672,
      "lng": 54.6031
    },
    "gm_rating": 4.6,
    "gm_reviews": 2681,
    "activity_rating": 4.43,
    "recommendation_score": 70,
    "overall_rank": 56,
    "category_rank": 2,
    "category_total": 7,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "yas-marina-2",
    "num": 94,
    "category": "adventure",
    "area": "Yas Island",
    "place": "Yas Marina Circuit",
    "address": "Yas Marina Circuit, Yas Island",
    "station": "Yas Marina",
    "photo_folder": "yas-marina-2",
    "scores": {
      "photo": 5,
      "culture": 3,
      "activity": 4,
      "relaxation": 3,
      "peaceful": 3,
      "couple": 5,
      "family": 4,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4672,
      "lng": 54.6031
    },
    "gm_rating": 4.6,
    "gm_reviews": 2681,
    "activity_rating": 4.16,
    "recommendation_score": 70,
    "overall_rank": 57,
    "category_rank": 3,
    "category_total": 7,
    "fame_stars": 4,
    "uniqueness": 4
  },
  {
    "id": "waterworld-1",
    "num": 95,
    "category": "themepark",
    "area": "Yas Island",
    "place": "Yas Waterworld",
    "address": "Yas Island, Abu Dhabi",
    "station": "Yas Island",
    "photo_folder": "waterworld-1",
    "scores": {
      "photo": 5,
      "culture": 1,
      "activity": 5,
      "relaxation": 2,
      "peaceful": 1,
      "couple": 4,
      "family": 5,
      "solo": 3,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4876,
      "lng": 54.5997
    },
    "gm_rating": 4.5,
    "gm_reviews": 19817,
    "activity_rating": 4.36,
    "recommendation_score": 91,
    "overall_rank": 15,
    "category_rank": 4,
    "category_total": 28,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "waterworld-2",
    "num": 96,
    "category": "themepark",
    "area": "Yas Island",
    "place": "Yas Waterworld",
    "address": "Yas Island, Abu Dhabi",
    "station": "Yas Island",
    "photo_folder": "waterworld-2",
    "scores": {
      "photo": 5,
      "culture": 1,
      "activity": 5,
      "relaxation": 3,
      "peaceful": 2,
      "couple": 4,
      "family": 5,
      "solo": 3,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4876,
      "lng": 54.5997
    },
    "gm_rating": 4.5,
    "gm_reviews": 19817,
    "activity_rating": 4.59,
    "recommendation_score": 91,
    "overall_rank": 16,
    "category_rank": 5,
    "category_total": 28,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "waterworld-3",
    "num": 97,
    "category": "themepark",
    "area": "Yas Island",
    "place": "Yas Waterworld",
    "address": "Yas Island, Abu Dhabi",
    "station": "Yas Island",
    "photo_folder": "waterworld-3",
    "scores": {
      "photo": 5,
      "culture": 1,
      "activity": 5,
      "relaxation": 2,
      "peaceful": 1,
      "couple": 3,
      "family": 5,
      "solo": 3,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4876,
      "lng": 54.5997
    },
    "gm_rating": 4.5,
    "gm_reviews": 19817,
    "activity_rating": 4.65,
    "recommendation_score": 91,
    "overall_rank": 17,
    "category_rank": 6,
    "category_total": 28,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "waterworld-4",
    "num": 98,
    "category": "themepark",
    "area": "Yas Island",
    "place": "Yas Waterworld",
    "address": "Yas Island, Abu Dhabi",
    "station": "Yas Island",
    "photo_folder": "waterworld-4",
    "scores": {
      "photo": 4,
      "culture": 1,
      "activity": 5,
      "relaxation": 3,
      "peaceful": 2,
      "couple": 4,
      "family": 5,
      "solo": 3,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4876,
      "lng": 54.5997
    },
    "gm_rating": 4.5,
    "gm_reviews": 19817,
    "activity_rating": 4.76,
    "recommendation_score": 90,
    "overall_rank": 19,
    "category_rank": 8,
    "category_total": 28,
    "fame_stars": 5,
    "uniqueness": 5
  },
  {
    "id": "zayed-sports",
    "num": 99,
    "category": "adventure",
    "area": "Zayed Sports City",
    "place": "Zayed Sports City",
    "address": "Zayed Sports City, Abu Dhabi",
    "station": "없음",
    "photo_folder": "zayed-sports",
    "scores": {
      "photo": 3,
      "culture": 2,
      "activity": 5,
      "relaxation": 2,
      "peaceful": 2,
      "couple": 3,
      "family": 4,
      "solo": 4,
      "tourist": 3,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.4345,
      "lng": 54.4455
    },
    "gm_rating": 4.5,
    "gm_reviews": 9530,
    "activity_rating": 4.5,
    "recommendation_score": 49,
    "overall_rank": 97,
    "category_rank": 6,
    "category_total": 7,
    "fame_stars": 4,
    "uniqueness": 2
  },
  {
    "id": "zero-latency",
    "num": 100,
    "category": "themepark",
    "area": "Al Maryah Island",
    "place": "Zero Latency",
    "address": "Al Maryah Island, Abu Dhabi",
    "station": "Yas Mall",
    "photo_folder": "zero-latency",
    "scores": {
      "photo": 3,
      "culture": 1,
      "activity": 5,
      "relaxation": 1,
      "peaceful": 1,
      "couple": 4,
      "family": 4,
      "solo": 4,
      "tourist": 4,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.5005,
      "lng": 54.394
    },
    "gm_rating": 4.9,
    "gm_reviews": 2445,
    "activity_rating": 4.9,
    "recommendation_score": 91,
    "overall_rank": 18,
    "category_rank": 7,
    "category_total": 28,
    "fame_stars": 4,
    "uniqueness": 5
  },
  {
    "id": "zuma",
    "num": 101,
    "category": "dining",
    "area": "Al Maryah Island",
    "place": "Zuma",
    "address": "Al Maryah Island, Abu Dhabi",
    "station": "Maryah Island",
    "photo_folder": "zuma",
    "scores": {
      "photo": 4,
      "culture": 3,
      "activity": 2,
      "relaxation": 4,
      "peaceful": 3,
      "couple": 5,
      "family": 3,
      "solo": 4,
      "tourist": 5,
      "accessibility": 4
    },
    "coordinates": {
      "lat": 24.5005,
      "lng": 54.394
    },
    "gm_rating": 4.4,
    "gm_reviews": 2481,
    "activity_rating": 4.4,
    "recommendation_score": 78,
    "overall_rank": 41,
    "category_rank": 4,
    "category_total": 18,
    "fame_stars": 4,
    "uniqueness": 5
  }
];
